package tunglt;

import java.awt.GridLayout;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Le Thanh Tung
 */
public class ClientUI extends javax.swing.JFrame {
    int m1 = 0, n1 = 0, m2 = 0, n2 = 0;
    public Client client;
    public Thread clientThread;
    JTextField[][] tfMaTran1;
    JTextField[][] tfMaTran2;
    
    public ClientUI() {
        initComponents();
        setResizable(false);
        setSize(1025, 670);
        setLocationRelativeTo(null);
        error.setVisible(false);
        send.setVisible(false);
        taResult.setEditable(false);
        
        this.addWindowListener(new WindowListener() {
            @Override public void windowOpened(WindowEvent e) {}
            @Override public void windowClosing(WindowEvent e) {
                try{
                    client.send(new Data("exit", null, 0, 0, null, 0, 0));
                    System.exit(0);
                }
                catch(Exception ex){}
            }
            @Override public void windowClosed(WindowEvent e) {}
            @Override public void windowIconified(WindowEvent e) {}
            @Override public void windowDeiconified(WindowEvent e) {}
            @Override public void windowActivated(WindowEvent e) {}
            @Override public void windowDeactivated(WindowEvent e) {}
        });
        
        try {
            client = new Client(this);
            clientThread = new Thread(client);
            clientThread.start();
        }
        catch(Exception ex){
            JOptionPane.showMessageDialog(this, "Không thể kết nối đến máy chủ.");
            System.exit(0);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        error = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfM1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfN1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        pMaTran1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfM2 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfN2 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        pMaTran2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        send = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        taResult = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(51, 153, 255));

        error.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        error.setForeground(java.awt.Color.red);
        error.setText("aaaaa");

        jPanel6.setBackground(new java.awt.Color(255, 255, 204));
        jPanel6.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setText("Ma trận thứ nhất:");
        jPanel6.add(jLabel11);
        jLabel11.setBounds(10, 11, 200, 29);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Size:");
        jPanel6.add(jLabel12);
        jLabel12.setBounds(228, 21, 28, 17);

        tfM1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfM1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM1KeyTyped(evt);
            }
        });
        jPanel6.add(tfM1);
        tfM1.setBounds(260, 18, 60, 23);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("x");
        jPanel6.add(jLabel13);
        jLabel13.setBounds(324, 21, 8, 17);

        tfN1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfN1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM1KeyTyped(evt);
            }
        });
        jPanel6.add(tfN1);
        tfN1.setBounds(336, 18, 60, 23);

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        pMaTran1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pMaTran1Layout = new javax.swing.GroupLayout(pMaTran1);
        pMaTran1.setLayout(pMaTran1Layout);
        pMaTran1Layout.setHorizontalGroup(
            pMaTran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        pMaTran1Layout.setVerticalGroup(
            pMaTran1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(pMaTran1);

        jPanel6.add(jScrollPane1);
        jScrollPane1.setBounds(10, 50, 430, 240);

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setLayout(null);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Ma trận thứ hai:");
        jPanel7.add(jLabel14);
        jLabel14.setBounds(10, 11, 200, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Size:");
        jPanel7.add(jLabel15);
        jLabel15.setBounds(228, 21, 28, 17);

        tfM2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfM2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM1KeyTyped(evt);
            }
        });
        jPanel7.add(tfM2);
        tfM2.setBounds(260, 18, 60, 23);

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("x");
        jPanel7.add(jLabel16);
        jLabel16.setBounds(324, 21, 8, 17);

        tfN2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tfN2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfM1KeyTyped(evt);
            }
        });
        jPanel7.add(tfN2);
        tfN2.setBounds(336, 18, 60, 23);

        pMaTran2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pMaTran2Layout = new javax.swing.GroupLayout(pMaTran2);
        pMaTran2.setLayout(pMaTran2Layout);
        pMaTran2Layout.setHorizontalGroup(
            pMaTran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 428, Short.MAX_VALUE)
        );
        pMaTran2Layout.setVerticalGroup(
            pMaTran2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 238, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(pMaTran2);

        jPanel7.add(jScrollPane2);
        jScrollPane2.setBounds(10, 50, 430, 240);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Set Size");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        send.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        send.setText("RESULT");
        send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(51, 153, 255));
        jPanel2.setLayout(null);

        taResult.setColumns(20);
        taResult.setRows(5);
        jScrollPane3.setViewportView(taResult);

        jPanel2.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 980, 260);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(error, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(send, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(send)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1040, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String a = tfM1.getText();
        String b = tfN1.getText();
        String c = tfM2.getText();
        String d = tfN2.getText();
        
        if (!(a.isEmpty()||b.isEmpty()||c.isEmpty()||d.isEmpty())){
            m1 = Integer.parseInt(a);
            n1 = Integer.parseInt(b);
            m2 = Integer.parseInt(c);
            n2 = Integer.parseInt(d);
            if (n1 == m2) {
                send.setVisible(true);
                pMaTran1.removeAll();
                pMaTran2.removeAll();
                error.setVisible(false);
                
                tfMaTran1 = new JTextField[m1][n1];
                tfMaTran2 = new JTextField[m2][n2];

                for(int i=0; i<m1; i++){
                    for(int j=0; j<n1; j++){
                        tfMaTran1[i][j] = new JTextField("0");
                        pMaTran1.add(tfMaTran1[i][j]);
                    }
                }

                for(int i=0; i<m2; i++){
                    for(int j=0; j<n2; j++){
                        tfMaTran2[i][j] = new JTextField("0");
                        pMaTran2.add(tfMaTran2[i][j]);
                    }
                }

                pMaTran1.setLayout(new GridLayout(m1,n1));
                pMaTran1.setVisible(false);
                pMaTran1.setVisible(true);
                pMaTran2.setLayout(new GridLayout(m2,n2));
                pMaTran2.setVisible(false);
                pMaTran2.setVisible(true);
            }
            else{
                send.setVisible(false);
                error.setVisible(true);
                error.setText("Hai ma trận này không thể nhân với nhau được.");
            }
        }
        else{
            send.setVisible(false);
            error.setVisible(true);
            error.setText("Chưa nhập đủ thông tin.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfM1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfM1KeyTyped
        char key = evt.getKeyChar();
        if (!Character.isDigit(key)) {
            evt.consume();
        }
    }//GEN-LAST:event_tfM1KeyTyped

    private void sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendActionPerformed
        error.setVisible(false);
        float[][] maTran1 = new float[m1][n1];
        float[][] maTran2 = new float[m2][n2];
        try{
            for(int i=0; i<m1; i++){
                for(int j=0; j<n1; j++){
                    maTran1[i][j] = Float.parseFloat(tfMaTran1[i][j].getText());
                }
            }

            for(int i=0; i<m2; i++){
                for(int j=0; j<n2; j++){
                    maTran2[i][j] = Float.parseFloat(tfMaTran2[i][j].getText());
                }
            }
            
            client.send(new Data("", maTran1, m1, n1, maTran2, m2, n2));
        }catch(Exception ex){
            error.setVisible(true);
            error.setText("Dữ liệu bạn nhập không hợp lệ");
        }
        
        
        
    }//GEN-LAST:event_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel error;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JPanel pMaTran1;
    public javax.swing.JPanel pMaTran2;
    public javax.swing.JButton send;
    public javax.swing.JTextArea taResult;
    public javax.swing.JTextField tfM1;
    public javax.swing.JTextField tfM2;
    public javax.swing.JTextField tfN1;
    public javax.swing.JTextField tfN2;
    // End of variables declaration//GEN-END:variables
}
