package tunglt;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;

/**
 *
 * @author Le Thanh Tung
 */
public class ServerUI extends javax.swing.JFrame {

    public Server server;
    
    public ServerUI() {
        initComponents();
        setSize(495, 190);
        setLocationRelativeTo(null);
        jPanel1.setVisible(false);
        setResizable(false);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        taServer.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        taServer = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        bStartServer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("START SERVER");
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        taServer.setColumns(20);
        taServer.setRows(5);
        jScrollPane1.setViewportView(taServer);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 10, 570, 450);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 590, 470);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        bStartServer.setBackground(java.awt.Color.cyan);
        bStartServer.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        bStartServer.setForeground(new java.awt.Color(255, 255, 255));
        bStartServer.setText("START SERVER");
        bStartServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartServerActionPerformed(evt);
            }
        });
        jPanel2.add(bStartServer);
        bStartServer.setBounds(100, 50, 300, 50);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 490, 160);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bStartServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartServerActionPerformed
        server = new Server(this);
        
        jPanel1.setVisible(true);
        jPanel2.setVisible(false);
        setTitle("SERVER");
        setSize(595, 500);
        taServer.append(nowTime() + ": Server đã khởi động.\n");

        setVisible(false);
        setLocationRelativeTo(null);
        setVisible(true);
    }//GEN-LAST:event_bStartServerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }
    
    public String nowTime(){
        return (new SimpleDateFormat("HH:mm:ss dd/MM/yyyy").format(new Date().getTime()));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bStartServer;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea taServer;
    // End of variables declaration//GEN-END:variables
}
